# rebuild-kernel.sh -- GENERATED by build-kernel-tcc.sh.  Do not edit.
# Rebuilds the kernel inside Makar via /apps/tcc.elf, then writes
# /bin/makar.kernel.tcc.  Copy to /boot/makar.kernel and reboot to test.
# Output dir /bin lives on the rootfs (created by the installer);
# tmpfs is flat so /tmp can't host the per-source .o tree.

echo rebuild-kernel: BEGIN
mkdir /bin/ktcc
FAILED=0

# _kernel_end sentinel is shipped at /apps/kend.S (kernel sh has no > redir).
exec /apps/tcc.elf -c /apps/kend.S -o /bin/ktcc/kend.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL kend; FAILED=1; fi

echo rebuild-kernel: cc src/kernel/arch/i386/boot/boot.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/boot.S -o /bin/ktcc/001.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/boot.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/build_origin.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/build_origin.c -o /bin/ktcc/002.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/build_origin.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/mb2_header_check.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/mb2_header_check.c -o /bin/ktcc/003.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/mb2_header_check.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/crti.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/crti.S -o /bin/ktcc/004.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/crti.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/crtn.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/crtn.S -o /bin/ktcc/005.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/crtn.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/dt_asm.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/dt_asm.S -o /bin/ktcc/006.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/dt_asm.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/descr_tbl.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/descr_tbl.c -o /bin/ktcc/007.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/descr_tbl.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/isr_asm.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/isr_asm.S -o /bin/ktcc/008.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/isr_asm.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/isr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/isr.c -o /bin/ktcc/009.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/isr.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/serial.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/serial.c -o /bin/ktcc/010.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/serial.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/timer.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/timer.c -o /bin/ktcc/011.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/timer.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/keyboard.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/keyboard.c -o /bin/ktcc/012.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/keyboard.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/ide.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/ide.c -o /bin/ktcc/013.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/ide.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/partition.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/partition.c -o /bin/ktcc/014.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/partition.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/acpi.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/acpi.c -o /bin/ktcc/015.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/acpi.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/rtc.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/rtc.c -o /bin/ktcc/016.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/rtc.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/fat32.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/fat32.c -o /bin/ktcc/017.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/fat32.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/ext2.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/ext2.c -o /bin/ktcc/018.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/ext2.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/iso9660.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/iso9660.c -o /bin/ktcc/019.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/iso9660.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/procfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/procfs.c -o /bin/ktcc/020.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/procfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/devfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/devfs.c -o /bin/ktcc/021.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/devfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/logfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/logfs.c -o /bin/ktcc/022.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/logfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/tmpfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/tmpfs.c -o /bin/ktcc/023.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/tmpfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/vfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/vfs.c -o /bin/ktcc/024.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/vfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/pmm.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/pmm.c -o /bin/ktcc/025.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/pmm.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/paging.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/paging.c -o /bin/ktcc/026.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/paging.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/heap.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/heap.c -o /bin/ktcc/027.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/heap.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/vmm.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/vmm.c -o /bin/ktcc/028.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/vmm.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/tty.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/tty.c -o /bin/ktcc/029.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/tty.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/vesa.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/vesa.c -o /bin/ktcc/030.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/vesa.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/vesa_tty.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/vesa_tty.c -o /bin/ktcc/031.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/vesa_tty.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/vt.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/vt.c -o /bin/ktcc/032.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/vt.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/bochs_vbe.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/bochs_vbe.c -o /bin/ktcc/033.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/bochs_vbe.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/system.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/system.c -o /bin/ktcc/034.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/system.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/task_asm.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/task_asm.S -o /bin/ktcc/035.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/task_asm.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/task.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/task.c -o /bin/ktcc/036.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/task.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/syscall.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/syscall.c -o /bin/ktcc/037.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/syscall.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/signal.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/signal.c -o /bin/ktcc/038.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/signal.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/fd.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/fd.c -o /bin/ktcc/039.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/fd.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/ring3.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/ring3.S -o /bin/ktcc/040.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/ring3.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/chainload.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/chainload.S -o /bin/ktcc/041.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/chainload.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/elf.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/elf.c -o /bin/ktcc/042.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/elf.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/usertest.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/usertest.c -o /bin/ktcc/043.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/usertest.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/ktest.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/ktest.c -o /bin/ktcc/044.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/ktest.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/installer.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/installer.c -o /bin/ktcc/045.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/installer.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/vtty.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/vtty.c -o /bin/ktcc/046.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/vtty.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell.c -o /bin/ktcc/047.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_glob.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_glob.c -o /bin/ktcc/048.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_glob.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_help.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_help.c -o /bin/ktcc/049.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_help.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_display.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_display.c -o /bin/ktcc/050.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_display.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_system.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_system.c -o /bin/ktcc/051.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_system.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_disk.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_disk.c -o /bin/ktcc/052.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_disk.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_fs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_fs.c -o /bin/ktcc/053.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_fs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_apps.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_apps.c -o /bin/ktcc/054.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_apps.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_man.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_man.c -o /bin/ktcc/055.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_man.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_script.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_script.c -o /bin/ktcc/056.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_script.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/sh_script.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/sh_script.c -o /bin/ktcc/057.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/sh_script.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/debug/debug.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/debug/debug.c -o /bin/ktcc/058.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/debug/debug.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/kernel/kernel.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/kernel/kernel.c -o /bin/ktcc/059.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/kernel/kernel.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memcmp.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memcmp.c -o /bin/ktcc/060.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memcmp.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memcpy.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memcpy.c -o /bin/ktcc/061.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memcpy.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memmove.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memmove.c -o /bin/ktcc/062.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memmove.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memset.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memset.c -o /bin/ktcc/063.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memset.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strcat.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strcat.c -o /bin/ktcc/064.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strcat.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strchr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strchr.c -o /bin/ktcc/065.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strchr.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strcmp.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strcmp.c -o /bin/ktcc/066.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strcmp.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strcpy.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strcpy.c -o /bin/ktcc/067.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strcpy.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strlen.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strlen.c -o /bin/ktcc/068.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strlen.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strncmp.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strncmp.c -o /bin/ktcc/069.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strncmp.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strncpy.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strncpy.c -o /bin/ktcc/070.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strncpy.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strrchr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strrchr.c -o /bin/ktcc/071.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strrchr.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strstr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strstr.c -o /bin/ktcc/072.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strstr.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdio/printf.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdio/printf.c -o /bin/ktcc/073.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdio/printf.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdio/putchar.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdio/putchar.c -o /bin/ktcc/074.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdio/putchar.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdio/puts.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdio/puts.c -o /bin/ktcc/075.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdio/puts.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdlib/abort.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdlib/abort.c -o /bin/ktcc/076.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdlib/abort.c; FAILED=1; fi

echo rebuild-kernel: archive
rm /bin/ktcc/libk.a
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/002.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/003.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/004.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/005.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/006.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/007.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/008.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/009.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/010.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/011.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/012.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/013.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/014.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/015.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/016.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/017.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/018.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/019.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/020.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/021.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/022.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/023.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/024.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/025.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/026.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/027.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/028.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/029.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/030.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/031.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/032.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/033.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/034.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/035.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/036.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/037.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/038.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/039.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/040.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/041.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/042.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/043.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/044.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/045.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/046.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/047.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/048.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/049.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/050.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/051.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/052.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/053.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/054.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/055.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/056.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/057.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/058.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/059.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/060.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/061.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/062.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/063.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/064.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/065.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/066.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/067.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/068.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/069.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/070.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/071.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/072.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/073.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/074.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/075.o
exec /apps/tcc.elf -ar rcs /bin/ktcc/libk.a /bin/ktcc/076.o

echo rebuild-kernel: link
exec /apps/tcc.elf -nostdlib -nostdinc -static -Wl,-Ttext=0x100000 -Wl,-section-alignment=0x1000 -o /bin/makar.kernel.tcc /bin/ktcc/001.o -Wl,--whole-archive /bin/ktcc/libk.a -Wl,--no-whole-archive /usr/lib/tcc/libtcc1.a /bin/ktcc/kend.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL link; FAILED=1; fi

if [ $FAILED -eq 0 ]; then
  echo REBUILD-KERNEL: ALL PASS
  echo rebuild-kernel: cp /bin/makar.kernel.tcc /boot/makar.kernel and reboot
else
  echo REBUILD-KERNEL: FAIL
fi
