# rebuild-kernel.sh -- GENERATED by build-kernel-tcc.sh.  Do not edit.
# Rebuilds the kernel inside Makar via /apps/tcc.elf, then writes
# $DIR/makar.kernel.tcc.  Copy to /boot/makar.kernel and reboot to test.
#
# Scratch dir: tries /bin first (persistent on HDD installs; created
# by the installer), falls back to /tmp on read-only-rootfs boots
# (live CD).  tmpfs now supports nested paths so either works.

echo rebuild-kernel: BEGIN
mkdir /bin/ktcc
if [ $? -eq 0 ]; then DIR=/bin; else DIR=/tmp; mkdir /tmp/ktcc; fi
echo rebuild-kernel: scratch $DIR/ktcc
FAILED=0

# _kernel_end sentinel is shipped at /apps/kend.S (kernel sh has no > redir).
exec /apps/tcc.elf -c /apps/kend.S -o $DIR/ktcc/kend.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL kend; FAILED=1; fi

echo rebuild-kernel: cc src/kernel/arch/i386/boot/boot.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/boot.S -o $DIR/ktcc/001.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/boot.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/build_origin.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/build_origin.c -o $DIR/ktcc/002.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/build_origin.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/mb2_header_check.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/mb2_header_check.c -o $DIR/ktcc/003.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/mb2_header_check.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/crti.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/crti.S -o $DIR/ktcc/004.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/crti.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/boot/crtn.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/boot/crtn.S -o $DIR/ktcc/005.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/boot/crtn.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/dt_asm.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/dt_asm.S -o $DIR/ktcc/006.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/dt_asm.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/descr_tbl.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/descr_tbl.c -o $DIR/ktcc/007.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/descr_tbl.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/isr_asm.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/isr_asm.S -o $DIR/ktcc/008.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/isr_asm.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/core/isr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/core/isr.c -o $DIR/ktcc/009.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/core/isr.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/serial.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/serial.c -o $DIR/ktcc/010.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/serial.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/timer.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/timer.c -o $DIR/ktcc/011.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/timer.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/keyboard.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/keyboard.c -o $DIR/ktcc/012.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/keyboard.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/ide.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/ide.c -o $DIR/ktcc/013.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/ide.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/partition.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/partition.c -o $DIR/ktcc/014.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/partition.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/acpi.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/acpi.c -o $DIR/ktcc/015.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/acpi.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/drivers/rtc.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/drivers/rtc.c -o $DIR/ktcc/016.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/drivers/rtc.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/fat32.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/fat32.c -o $DIR/ktcc/017.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/fat32.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/ext2.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/ext2.c -o $DIR/ktcc/018.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/ext2.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/iso9660.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/iso9660.c -o $DIR/ktcc/019.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/iso9660.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/procfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/procfs.c -o $DIR/ktcc/020.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/procfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/devfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/devfs.c -o $DIR/ktcc/021.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/devfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/logfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/logfs.c -o $DIR/ktcc/022.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/logfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/tmpfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/tmpfs.c -o $DIR/ktcc/023.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/tmpfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/fs/vfs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/fs/vfs.c -o $DIR/ktcc/024.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/fs/vfs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/pmm.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/pmm.c -o $DIR/ktcc/025.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/pmm.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/paging.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/paging.c -o $DIR/ktcc/026.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/paging.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/heap.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/heap.c -o $DIR/ktcc/027.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/heap.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/mm/vmm.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/mm/vmm.c -o $DIR/ktcc/028.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/mm/vmm.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/tty.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/tty.c -o $DIR/ktcc/029.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/tty.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/vesa.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/vesa.c -o $DIR/ktcc/030.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/vesa.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/vesa_tty.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/vesa_tty.c -o $DIR/ktcc/031.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/vesa_tty.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/vt.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/vt.c -o $DIR/ktcc/032.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/vt.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/display/bochs_vbe.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/display/bochs_vbe.c -o $DIR/ktcc/033.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/display/bochs_vbe.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/system.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/system.c -o $DIR/ktcc/034.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/system.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/task_asm.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/task_asm.S -o $DIR/ktcc/035.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/task_asm.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/task.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/task.c -o $DIR/ktcc/036.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/task.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/syscall.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/syscall.c -o $DIR/ktcc/037.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/syscall.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/signal.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/signal.c -o $DIR/ktcc/038.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/signal.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/fd.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/fd.c -o $DIR/ktcc/039.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/fd.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/ring3.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/ring3.S -o $DIR/ktcc/040.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/ring3.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/chainload.S
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/chainload.S -o $DIR/ktcc/041.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/chainload.S; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/elf.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/elf.c -o $DIR/ktcc/042.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/elf.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/usertest.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/usertest.c -o $DIR/ktcc/043.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/usertest.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/ktest.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/ktest.c -o $DIR/ktcc/044.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/ktest.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/installer.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/installer.c -o $DIR/ktcc/045.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/installer.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/proc/vtty.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/proc/vtty.c -o $DIR/ktcc/046.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/proc/vtty.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell.c -o $DIR/ktcc/047.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_glob.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_glob.c -o $DIR/ktcc/048.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_glob.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_help.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_help.c -o $DIR/ktcc/049.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_help.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_display.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_display.c -o $DIR/ktcc/050.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_display.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_system.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_system.c -o $DIR/ktcc/051.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_system.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_disk.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_disk.c -o $DIR/ktcc/052.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_disk.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_fs.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_fs.c -o $DIR/ktcc/053.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_fs.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_apps.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_apps.c -o $DIR/ktcc/054.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_apps.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_man.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_man.c -o $DIR/ktcc/055.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_man.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/shell_cmd_script.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/shell_cmd_script.c -o $DIR/ktcc/056.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/shell_cmd_script.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/shell/sh_script.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/shell/sh_script.c -o $DIR/ktcc/057.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/shell/sh_script.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/arch/i386/debug/debug.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/arch/i386/debug/debug.c -o $DIR/ktcc/058.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/arch/i386/debug/debug.c; FAILED=1; fi
echo rebuild-kernel: cc src/kernel/kernel/kernel.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/kernel/kernel/kernel.c -o $DIR/ktcc/059.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/kernel/kernel/kernel.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memcmp.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memcmp.c -o $DIR/ktcc/060.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memcmp.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memcpy.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memcpy.c -o $DIR/ktcc/061.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memcpy.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memmove.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memmove.c -o $DIR/ktcc/062.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memmove.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/memset.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/memset.c -o $DIR/ktcc/063.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/memset.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strcat.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strcat.c -o $DIR/ktcc/064.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strcat.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strchr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strchr.c -o $DIR/ktcc/065.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strchr.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strcmp.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strcmp.c -o $DIR/ktcc/066.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strcmp.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strcpy.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strcpy.c -o $DIR/ktcc/067.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strcpy.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strlen.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strlen.c -o $DIR/ktcc/068.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strlen.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strncmp.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strncmp.c -o $DIR/ktcc/069.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strncmp.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strncpy.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strncpy.c -o $DIR/ktcc/070.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strncpy.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strrchr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strrchr.c -o $DIR/ktcc/071.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strrchr.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/string/strstr.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/string/strstr.c -o $DIR/ktcc/072.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/string/strstr.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdio/printf.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdio/printf.c -o $DIR/ktcc/073.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdio/printf.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdio/putchar.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdio/putchar.c -o $DIR/ktcc/074.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdio/putchar.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdio/puts.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdio/puts.c -o $DIR/ktcc/075.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdio/puts.c; FAILED=1; fi
echo rebuild-kernel: cc src/libc/stdlib/abort.c
exec /apps/tcc.elf -ffreestanding -D__is_kernel -DDEV_BUILD -DMAKAR_IN_OS_BUILD=1 -I/usr/include/kernel-build -c /src/libc/stdlib/abort.c -o $DIR/ktcc/076.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL src/libc/stdlib/abort.c; FAILED=1; fi

echo rebuild-kernel: link
exec /apps/tcc.elf -nostdlib -nostdinc -static -Wl,-Ttext=0x100000 -Wl,-section-alignment=0x1000 -o $DIR/makar.kernel.tcc $DIR/ktcc/001.o $DIR/ktcc/002.o $DIR/ktcc/003.o $DIR/ktcc/004.o $DIR/ktcc/005.o $DIR/ktcc/006.o $DIR/ktcc/007.o $DIR/ktcc/008.o $DIR/ktcc/009.o $DIR/ktcc/010.o $DIR/ktcc/011.o $DIR/ktcc/012.o $DIR/ktcc/013.o $DIR/ktcc/014.o $DIR/ktcc/015.o $DIR/ktcc/016.o $DIR/ktcc/017.o $DIR/ktcc/018.o $DIR/ktcc/019.o $DIR/ktcc/020.o $DIR/ktcc/021.o $DIR/ktcc/022.o $DIR/ktcc/023.o $DIR/ktcc/024.o $DIR/ktcc/025.o $DIR/ktcc/026.o $DIR/ktcc/027.o $DIR/ktcc/028.o $DIR/ktcc/029.o $DIR/ktcc/030.o $DIR/ktcc/031.o $DIR/ktcc/032.o $DIR/ktcc/033.o $DIR/ktcc/034.o $DIR/ktcc/035.o $DIR/ktcc/036.o $DIR/ktcc/037.o $DIR/ktcc/038.o $DIR/ktcc/039.o $DIR/ktcc/040.o $DIR/ktcc/041.o $DIR/ktcc/042.o $DIR/ktcc/043.o $DIR/ktcc/044.o $DIR/ktcc/045.o $DIR/ktcc/046.o $DIR/ktcc/047.o $DIR/ktcc/048.o $DIR/ktcc/049.o $DIR/ktcc/050.o $DIR/ktcc/051.o $DIR/ktcc/052.o $DIR/ktcc/053.o $DIR/ktcc/054.o $DIR/ktcc/055.o $DIR/ktcc/056.o $DIR/ktcc/057.o $DIR/ktcc/058.o $DIR/ktcc/059.o $DIR/ktcc/060.o $DIR/ktcc/061.o $DIR/ktcc/062.o $DIR/ktcc/063.o $DIR/ktcc/064.o $DIR/ktcc/065.o $DIR/ktcc/066.o $DIR/ktcc/067.o $DIR/ktcc/068.o $DIR/ktcc/069.o $DIR/ktcc/070.o $DIR/ktcc/071.o $DIR/ktcc/072.o $DIR/ktcc/073.o $DIR/ktcc/074.o $DIR/ktcc/075.o $DIR/ktcc/076.o /usr/lib/tcc/libtcc1.a $DIR/ktcc/kend.o
if [ $? -ne 0 ]; then echo rebuild-kernel: FAIL link; FAILED=1; fi

if [ $FAILED -eq 0 ]; then
  echo REBUILD-KERNEL: ALL PASS
  echo rebuild-kernel: cp $DIR/makar.kernel.tcc /boot/makar.kernel and reboot
else
  echo REBUILD-KERNEL: FAIL
fi
